# Generated by Django 2.2.4 on 2019-09-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='jedzonko.DayName'),
        ),
    ]
