# Generated by Django 2.2.4 on 2019-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20190922_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(),
        ),
    ]
